// RevenueDot: open-source, self-hostable alternative to RevenueCat. Same SDK API, free.
// This file: loads data/errors/*.json and renders each entry as a Markdown page under docs/errors/ (shared by gen-errors, check-errors and check-snippets).
// Docs: https://revenuedot.app/docs/errors   Migrate from RevenueCat: https://revenuedot.app/docs/migrate
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { ROOT } from "./pages.mjs";

export const DATA_DIR = join(ROOT, "data", "errors");
export const OUT_DIR = join(ROOT, "docs", "errors");
/** A page with fewer words than this is thin: it is not generated (set "draft": true on the entry until it has more). */
export const MIN_WORDS = 170;
export const GENERATED = "<!-- Generated by scripts/gen-errors.mjs";

/** Every data file, sorted by name, with its entries tagged by the file they came from. */
export function loadData() {
  return readdirSync(DATA_DIR).filter((f) => f.endsWith(".json")).sort().map((file) => {
    const set = JSON.parse(readFileSync(join(DATA_DIR, file), "utf8"));
    return { file, ...set, pages: set.pages.map((p) => ({ ...p, file, set: set.set })) };
  });
}

const FIELDS = ["slug", "label", "title", "description", "answer", "symbol", "api", "definition", "causes", "fixes", "snippet", "sdk", "related", "sources", "checked"];

/** Structural problems in an entry (missing fields, bad shapes). Returns a list of messages. */
export function validateEntry(p, slugs) {
  const out = [];
  for (const f of FIELDS) if (p[f] === undefined || p[f] === "" || (Array.isArray(p[f]) && !p[f].length)) out.push(`missing ${f}`);
  if (!/^[a-z0-9-]+$/.test(p.slug ?? "")) out.push("slug must be lower-case letters, digits and hyphens");
  if (typeof p.title === "string" && !p.title.trim().endsWith("?")) out.push("title must be a question");
  if (typeof p.description === "string" && (p.description.length > 300 || p.description.includes("\n"))) out.push("description must be one line of at most 300 characters");
  if (!/^\d{4}-\d{2}-\d{2}$/.test(p.checked ?? "")) out.push("checked must be YYYY-MM-DD");
  for (const r of p.related ?? []) if (!slugs.has(r)) out.push(`related page ${r} does not exist`);
  for (const s of p.sources ?? []) if (!/^https:\/\//.test(s.url ?? "") || !s.label) out.push("every source needs a label and an https URL");
  if (p.snippet && (!p.snippet.lang || !p.snippet.code || !["swift", "swift-sdk", "none"].includes(p.snippet.check))) out.push("snippet needs lang, code and check (swift, swift-sdk or none)");
  return out;
}

const esc = (s) => String(s).replace(/\|/g, "\\|");
const yaml = (s) => JSON.stringify(s);

/** The compile note under the code block: what was checked, or a plain "not compiled". */
function snippetNote(p) {
  const s = p.snippet;
  if (s.check === "swift") return `Compile-checked: \`npm run check:snippets\` type-checks this snippet with \`swiftc\` against the Apple SDK (macOS target, checked ${p.checked}).`;
  if (s.check === "swift-sdk") return `Compile-checked: \`npm run check:snippets\` type-checks this snippet with \`swiftc\` together with the \`ErrorCode.swift\` file of the RevenueDot \`purchases-ios\` fork (checked ${p.checked}).`;
  return `Not compiled: this ${s.lang === "kotlin" ? "Kotlin " : ""}snippet was not built here because the docs repo has no ${s.lang === "kotlin" ? "Kotlin or Android" : s.lang} toolchain. Check it against your Play Billing Library or SDK version before you ship it.`;
}

/** The Markdown of one page. */
export function renderPage(p, byslug) {
  const L = [];
  L.push("---", `title: ${yaml(p.title)}`, `description: ${yaml(p.description)}`, `label: ${yaml(p.label)}`, "---", "");
  L.push(`${GENERATED} from data/errors/${p.file}. Do not edit by hand; edit the data file and run npm run build. -->`, "");
  L.push(`# ${p.title}`, "", p.answer, "");
  L.push("## Quick facts", "", "| | |", "|---|---|", `| Error | ${esc(p.symbol)} |`, `| Where | ${esc(p.api)} |`);
  if (p.since) L.push(`| Available since | ${esc(p.since)} |`);
  L.push(`| What the vendor says | ${esc(p.definition)} |`, "");
  L.push("## Cause", "", ...p.causes.map((c) => `- ${c}`), "");
  L.push("## Fix", "", ...p.fixes.map((c, i) => `${i + 1}. ${c}`), "");
  L.push("## Example", "", "```" + p.snippet.lang, p.snippet.code.trimEnd(), "```", "", `*${snippetNote(p)}*`, "");
  L.push("## How the RevenueDot SDK reports it", "", p.sdk, "");
  L.push("## Related", "");
  for (const r of p.related) L.push(`- [${byslug.get(r).title}](${r}.md)`);
  for (const x of p.links ?? []) L.push(`- [${x.label}](${x.url})`);
  L.push("", "## Source", "", ...p.sources.map((s) => `- [${s.label}](${s.url})`), "", `Checked: ${p.checked}`, "");
  return L.join("\n");
}

const SETS = [
  { id: "storekit", heading: "Apple StoreKit 2 errors", blurb: "The error cases the StoreKit 2 Swift API throws when you load products, buy, refund or verify." },
  { id: "play-billing", heading: "Google Play Billing response codes", blurb: "The `BillingResponseCode` values that Play Billing Library calls return in a `BillingResult`." },
  { id: "sdk", heading: "Purchases SDK error codes", blurb: "The `ErrorCode` set of the purchases SDK, the same on RevenueDot as on RevenueCat." },
];

/** The index page: every generated page, grouped by data set. */
export function renderIndex(pages) {
  const L = [];
  L.push("---", `title: ${yaml("What do store and SDK error codes mean?")}`, `description: ${yaml("One page per Apple StoreKit 2 error, Google Play Billing response code and purchases SDK error code: what it means, why it happens, how to fix it, and where the vendor says so.")}`, `label: ${yaml("All error pages")}`, "---", "");
  L.push(`${GENERATED} from data/errors/*.json. Do not edit by hand; edit the data files and run npm run build. -->`, "");
  L.push("# What do store and SDK error codes mean?", "", `Each page below answers one error in a sentence, then gives the cause, the fix, an example and the vendor source it was checked against (${pages.length} pages). For the full list of RevenueDot server error codes, see [what RevenueDot's API errors mean](../../api/errors.md).`, "");
  for (const s of SETS) {
    const list = pages.filter((p) => p.set === s.id);
    if (!list.length) continue;
    L.push(`## ${s.heading}`, "", s.blurb, "", ...list.map((p) => `- [${p.title}](${p.slug}.md)`), "");
  }
  return L.join("\n");
}

export const wordCount = (md) => md.replace(/```[\s\S]*?```/g, " ").split(/\s+/).filter(Boolean).length;
