// RevenueDot: open-source, self-hostable alternative to RevenueCat. Same SDK API, free.
// This file: loads the reference data (data/errors, data/notifications, data/webhooks) and renders each entry as a Markdown page
// under docs/errors, docs/notifications or docs/webhooks (shared by gen-errors, check-errors and check-snippets).
// Docs: https://revenuedot.app/docs/errors   Migrate from RevenueCat: https://revenuedot.app/docs/migrate
import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { ROOT } from "./pages.mjs";

/** A page with fewer words than this is thin: it is not generated (set "draft": true on the entry until it has more). */
export const MIN_WORDS = 170;
export const GENERATED = "<!-- Generated by scripts/gen-errors.mjs";

/**
 * The three families of generated pages. `labels` are the section headings of a page; `sets` group a family's index page.
 * `requireRevenueDotSource`: the page states how RevenueDot behaves, so it must link the source file that says so.
 */
export const KINDS = [
  {
    id: "errors",
    labels: { symbol: "Error", cause: "Cause", fix: "Fix", mapping: "How the RevenueDot SDK reports it" },
    requireRevenueDotSource: false,
    index: {
      title: "What do store and SDK error codes mean?",
      description: "One page per Apple StoreKit 2 error, Google Play Billing response code and purchases SDK error code: what it means, why it happens, how to fix it, and where the vendor says so.",
      label: "All error pages",
      intro: (n) => `Each page below answers one error in a sentence, then gives the cause, the fix, an example and the vendor source it was checked against (${n} pages). For the full list of RevenueDot server error codes, see [what RevenueDot's API errors mean](../../api/errors.md).`,
    },
    sets: [
      { id: "storekit", heading: "Apple StoreKit 2 errors", blurb: "The error cases the StoreKit 2 Swift API throws when you load products, buy, refund or verify." },
      { id: "play-billing", heading: "Google Play Billing response codes", blurb: "The `BillingResponseCode` values that Play Billing Library calls return in a `BillingResult`." },
      { id: "sdk", heading: "Purchases SDK error codes", blurb: "The `ErrorCode` set of the purchases SDK, the same on RevenueDot as on RevenueCat." },
    ],
  },
  {
    id: "notifications",
    labels: { symbol: "Notification", cause: "What triggers it", fix: "What your server should do", mapping: "How RevenueDot handles it" },
    requireRevenueDotSource: true,
    index: {
      title: "What do App Store and Google Play server notifications mean?",
      description: "One page per Apple App Store Server Notifications v2 type and subtype and per Google Play real-time developer notification type: what triggers it, what your server should do, and how RevenueDot handles it.",
      label: "All notification pages",
      intro: (n) => `Each page below answers one store notification in a sentence, then gives what triggers it, what your server should do, an example you can run and how RevenueDot applies it (${n} pages). The events RevenueDot then sends to your own webhook are in [which webhook events RevenueDot sends](../../api/webhook-events.md).`,
    },
    sets: [
      { id: "apple", heading: "Apple App Store Server Notifications v2", blurb: "The `notificationType` and `subtype` values in the signed payload that the App Store posts to your server." },
      { id: "google", heading: "Google Play real-time developer notifications", blurb: "The notification types in the Pub/Sub message that Google Play publishes for subscriptions, one-time products and voided purchases." },
    ],
  },
  {
    id: "webhooks",
    labels: { symbol: "Event", cause: "When it is sent", fix: "What your server should do", mapping: "How RevenueDot produces it" },
    requireRevenueDotSource: true,
    index: {
      title: "What do RevenueDot webhook events mean?",
      description: "One page per RevenueDot webhook event type: when it is sent, what your server should do with it, how RevenueDot derives it from the store's data, and a webhook handler you can run.",
      label: "All webhook event pages",
      intro: (n) => `Each page below answers one webhook event in a sentence, then gives when it is sent, what your server should do, a handler you can run and the rule in RevenueDot's code that produces it (${n} pages). Every field of every event, with a recorded payload, is in [which webhook events RevenueDot sends](../../api/webhook-events.md).`,
    },
    sets: [
      { id: "revenuedot", heading: "The 21 event types", blurb: "RevenueCat's webhook event types, the same names and fields on RevenueDot. Two are accepted in a filter but never sent." },
    ],
  },
];
export const kindOf = (id) => KINDS.find((k) => k.id === id);
export const dataDir = (kind) => join(ROOT, "data", kind.id);
export const outDir = (kind) => join(ROOT, "docs", kind.id);
/** Legacy name: the folder of the first family. */
export const OUT_DIR = outDir(KINDS[0]);

/** Every data file of every family, sorted by family then name, with its entries tagged by the file and family they came from. */
export function loadData() {
  return KINDS.flatMap((kind) => {
    const dir = dataDir(kind);
    if (!existsSync(dir)) return [];
    return readdirSync(dir).filter((f) => f.endsWith(".json")).sort().map((file) => {
      const set = JSON.parse(readFileSync(join(dir, file), "utf8"));
      return { file, kind: kind.id, ...set, pages: set.pages.map((p) => ({ ...p, file, set: set.set, kind: kind.id })) };
    });
  });
}

const FIELDS = ["slug", "label", "title", "description", "answer", "symbol", "api", "definition", "causes", "fixes", "snippet", "related", "sources", "checked"];
const SNIPPET_CHECKS = ["swift", "swift-sdk", "node", "none"];
const toolchainOf = { swift: ["swift", "swift-sdk"], javascript: ["node"], js: ["node"] };
const VENDOR_HOSTS = /^https:\/\/(developer\.apple\.com|developer\.android\.com|developers\.google\.com|www\.revenuecat\.com|docs\.revenuecat\.com)\//;

/** Structural problems in an entry (missing fields, bad shapes). Returns a list of messages. */
export function validateEntry(p, slugs) {
  const out = [];
  for (const f of FIELDS) if (p[f] === undefined || p[f] === "" || (Array.isArray(p[f]) && !p[f].length)) out.push(`missing ${f}`);
  if (!(p.mapping ?? p.sdk)) out.push("missing mapping (how RevenueDot handles it; legacy field sdk for error pages)");
  if (!/^[a-z0-9-]+$/.test(p.slug ?? "")) out.push("slug must be lower-case letters, digits and hyphens");
  // The site falls back to "<label> | RevenueDot Docs" when a title is too long for a 70-character <title>, so the label must fit.
  if (typeof p.label === "string" && `${p.label} | RevenueDot Docs`.length > 70) out.push(`label is ${p.label.length} characters; at most 52 so "<label> | RevenueDot Docs" fits a 70-character title`);
  if (typeof p.title === "string" && !p.title.trim().endsWith("?")) out.push("title must be a question");
  if (typeof p.description === "string" && (p.description.length > 300 || p.description.includes("\n"))) out.push("description must be one line of at most 300 characters");
  if (!/^\d{4}-\d{2}-\d{2}$/.test(p.checked ?? "")) out.push("checked must be YYYY-MM-DD");
  for (const r of p.related ?? []) if (!slugs.has(r)) out.push(`related page ${r} does not exist`);
  for (const s of p.sources ?? []) if (!/^https:\/\//.test(s.url ?? "") || !s.label) out.push("every source needs a label and an https URL");
  const kind = kindOf(p.kind);
  const sources = p.sources ?? [];
  if (!sources.some((s) => VENDOR_HOSTS.test(s.url ?? "") || (p.kind !== "errors" && /^https:\/\/github\.com\/(apple|googleapis)\//.test(s.url ?? "")) || /^https:\/\/github\.com\/revenuedot\/purchases-/.test(s.url ?? ""))) out.push("needs a source from the vendor (Apple, Google or RevenueCat docs, or a purchases SDK file)");
  if (kind?.requireRevenueDotSource && !sources.some((s) => /^https:\/\/github\.com\/revenuedot\/revenuedot\/blob\/main\/(apps|packages)\//.test(s.url ?? ""))) out.push("needs a link to the RevenueDot server source file that implements the behavior it states");
  if (p.snippet) {
    const s = p.snippet;
    if (!s.lang || !s.code || !SNIPPET_CHECKS.includes(s.check)) out.push(`snippet needs lang, code and check (${SNIPPET_CHECKS.join(", ")})`);
    const needs = toolchainOf[s.lang];
    if (needs && !needs.includes(s.check)) out.push(`a ${s.lang} snippet must be checked (check: ${needs.join(" or ")}); this repo has that toolchain`);
    if (s.check === "node" && !s.expect) out.push('a node snippet needs "expect", text its output must contain');
    if (s.check === "node" && !/\bconsole\.log\(/.test(s.code ?? "")) out.push("a node snippet must print its result with console.log so the check can compare it");
  }
  if (p.kind === "webhooks" && !p.event) out.push('webhook entries need "event" (the type as sent, for example INITIAL_PURCHASE)');
  return out;
}

const esc = (s) => String(s).replace(/\|/g, "\\|");
const yaml = (s) => JSON.stringify(s);

/** The note under the code block: what was checked, or a plain "not compiled". */
function snippetNote(p) {
  const s = p.snippet;
  if (s.check === "swift") return `Compile-checked: \`npm run check:snippets\` type-checks this snippet with \`swiftc\` against the Apple SDK (macOS target, checked ${p.checked}).`;
  if (s.check === "swift-sdk") return `Compile-checked: \`npm run check:snippets\` type-checks this snippet with \`swiftc\` together with the \`ErrorCode.swift\` file of the RevenueDot \`purchases-ios\` fork (checked ${p.checked}).`;
  if (s.check === "node") return `Run-checked: \`npm run check:snippets\` runs this snippet with Node and compares its output with \`${s.expect}\` (checked ${p.checked}).`;
  return `Not compiled: this ${s.lang === "kotlin" ? "Kotlin " : ""}snippet was not built here because the docs repo has no ${s.lang === "kotlin" ? "Kotlin or Android" : s.lang} toolchain. Check it against your Play Billing Library or SDK version before you ship it.`;
}

/** The Markdown of one page. `byslug` holds every entry of every family, for the related links. */
export function renderPage(p, byslug) {
  const kind = kindOf(p.kind);
  const L = [];
  L.push("---", `title: ${yaml(p.title)}`, `description: ${yaml(p.description)}`, `label: ${yaml(p.label)}`, "---", "");
  L.push(`${GENERATED} from data/${p.kind}/${p.file}. Do not edit by hand; edit the data file and run npm run build. -->`, "");
  L.push(`# ${p.title}`, "", p.answer, "");
  L.push("## Quick facts", "", "| | |", "|---|---|", `| ${kind.labels.symbol} | ${esc(p.symbol)} |`, `| Where | ${esc(p.api)} |`);
  for (const [k, v] of p.facts ?? []) L.push(`| ${esc(k)} | ${esc(v)} |`);
  if (p.since) L.push(`| Available since | ${esc(p.since)} |`);
  L.push(`| ${p.definitionLabel ?? "What the vendor says"} | ${esc(p.definition)} |`, "");
  L.push(`## ${kind.labels.cause}`, "", ...p.causes.map((c) => `- ${c}`), "");
  L.push(`## ${kind.labels.fix}`, "", ...p.fixes.map((c, i) => `${i + 1}. ${c}`), "");
  L.push("## Example", "", "```" + p.snippet.lang, p.snippet.code.trimEnd(), "```", "", `*${snippetNote(p)}*`, "");
  L.push(`## ${kind.labels.mapping}`, "", p.mapping ?? p.sdk, "");
  L.push("## Related", "");
  for (const r of p.related) {
    const t = byslug.get(r);
    L.push(`- [${t.title}](${t.kind === p.kind ? "" : `../${t.kind}/`}${r}.md)`);
  }
  for (const x of p.links ?? []) L.push(`- [${x.label}](${x.url})`);
  L.push("", "## Source", "", ...p.sources.map((s) => `- [${s.label}](${s.url})`), "", `Checked: ${p.checked}`, "");
  return L.join("\n");
}

/** The index page of one family: every generated page, grouped by data set. */
export function renderIndex(kind, pages) {
  const L = [];
  const ix = kind.index;
  L.push("---", `title: ${yaml(ix.title)}`, `description: ${yaml(ix.description)}`, `label: ${yaml(ix.label)}`, "---", "");
  L.push(`${GENERATED} from data/${kind.id}/*.json. Do not edit by hand; edit the data files and run npm run build. -->`, "");
  L.push(`# ${ix.title}`, "", ix.intro(pages.length), "");
  for (const s of kind.sets) {
    const list = pages.filter((p) => p.set === s.id);
    if (!list.length) continue;
    L.push(`## ${s.heading}`, "", s.blurb, "", ...list.map((p) => `- [${p.title}](${p.slug}.md)`), "");
  }
  return L.join("\n");
}

export const wordCount = (md) => md.replace(/```[\s\S]*?```/g, " ").split(/\s+/).filter(Boolean).length;
