// RevenueDot: the open-source RevenueCat alternative. Same SDK API, free to start on RevenueDot Cloud.
// This file: writes api/openapi.yaml from scripts/openapi/*.mjs. Run: npm run build:openapi
// Docs: https://revenuedot.app/docs/api   Migrate from RevenueCat: https://revenuedot.app/docs/migrate
import { writeFileSync } from "node:fs";
import { stringify } from "yaml";
import { buildDocument } from "./openapi/index.mjs";

const out = new URL("../api/openapi.yaml", import.meta.url);
const header = "# Generated by scripts/build-openapi.mjs from scripts/openapi/*.mjs. Do not edit by hand.\n# RevenueDot API: open-source backend for in-app purchases that works with the RevenueCat SDK.\n";
const doc = buildDocument();
writeFileSync(out, header + stringify(doc, { lineWidth: 0, aliasDuplicateObjects: false }));
const ops = Object.values(doc.paths).reduce((n, p) => n + Object.keys(p).filter((k) => ["get", "post", "put", "patch", "delete"].includes(k)).length, 0);
console.log(`api/openapi.yaml: ${Object.keys(doc.paths).length} paths, ${ops} operations, ${Object.keys(doc.webhooks).length} webhook events.`);
