// RevenueDot: the open-source RevenueCat alternative. Same SDK API, free to start on RevenueDot Cloud.
// This file: the quality gate for the generated reference pages (docs/errors, docs/notifications, docs/webhooks). Fails a page that has no
// source link, no code block, a first sentence or code block shared with another page, no cause or fix, a missing compile or run note,
// an unchecked snippet where this repo has the toolchain, thin content, a webhook event that api/webhook-events.md does not list, or
// text that differs from the data file.
// Run: npm run check:errors
// Docs: https://revenuedot.app/docs/errors   Migrate from RevenueCat: https://revenuedot.app/docs/migrate
import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { GENERATED, KINDS, MIN_WORDS, loadData, outDir, renderIndex, renderPage, validateEntry, wordCount } from "./lib/errors.mjs";
import { ROOT, proseLines, readPage } from "./lib/pages.mjs";

const problems = [];
const fail = (rel, msg) => problems.push(`${rel}: ${msg}`);
const all = loadData().flatMap((s) => s.pages).filter((p) => !p.draft);
const bySlug = new Map(all.map((p) => [p.slug, p]));
const firstSentences = new Map();
const descriptions = new Map();
const snippets = new Map();
const unique = (map, key, rel, what) => { if (map.has(key)) fail(rel, `${what} is the same as ${map.get(key)}`); else map.set(key, rel); };
const events = existsSync(join(ROOT, "api/webhook-events.md")) ? readFileSync(join(ROOT, "api/webhook-events.md"), "utf8") : "";
let total = 0;

for (const kind of KINDS) {
  const dir = outDir(kind);
  const entries = all.filter((p) => p.kind === kind.id);
  const files = existsSync(dir) ? readdirSync(dir).filter((f) => f.endsWith(".md") && f !== "README.md") : [];
  const kslugs = new Map(entries.map((p) => [p.slug, p]));
  // Every non-draft entry has a page, and every page has an entry.
  for (const p of entries) if (!files.includes(`${p.slug}.md`)) fail(`data/${kind.id}/${p.file}`, `${p.slug} has no generated page; run npm run build:errors`);
  for (const f of files) if (!kslugs.has(f.replace(/\.md$/, ""))) fail(`docs/${kind.id}/${f}`, "no entry in data/ (stale or hand-written page)");

  for (const f of files) {
    const rel = `docs/${kind.id}/${f}`;
    const slug = f.replace(/\.md$/, "");
    const entry = kslugs.get(slug);
    const { raw, meta, body } = readPage(rel);
    if (!raw.includes(GENERATED)) fail(rel, "not generated by scripts/gen-errors.mjs");
    if (entry) {
      for (const m of validateEntry(entry, new Set(bySlug.keys()))) fail(rel, m);
      if (raw !== renderPage(entry, bySlug)) fail(rel, "differs from its data file; run npm run build:errors (never edit these pages by hand)");
      unique(descriptions, entry.description.toLowerCase(), rel, "description");
      unique(snippets, entry.snippet.code.replace(/\s+/g, " ").trim(), rel, "example code");
      // A sent event has its own heading in api/webhook-events.md; a never-sent one is named in the sentence that says RevenueDot never sends it.
      if (entry.kind === "webhooks" && !entry.neverSent && !new RegExp(`^## ${entry.event}$`, "m").test(events)) fail(rel, `event ${entry.event} is not a heading of api/webhook-events.md`);
      if (entry.kind === "webhooks" && entry.neverSent && !events.includes(`\`${entry.event}\``)) fail(rel, `never-sent event ${entry.event} is not named in api/webhook-events.md`);
    }
    const lines = proseLines(body).map((x) => x.line);
    const h1 = lines.findIndex((l) => /^#\s/.test(l));
    // The answer: the first paragraph after the H1.
    const para = [];
    for (const l of lines.slice(h1 + 1)) { if (!l.trim()) { if (para.length) break; continue; } if (/^#{1,6}\s/.test(l)) break; para.push(l.trim()); }
    const answer = para.join(" ");
    if (!answer) fail(rel, "no answer sentence under the H1");
    else {
      const sentences = answer.match(/[^.!?]+[.!?]+(\s|$)/g) ?? [];
      if (sentences.length !== 1 || !/[.!?]$/.test(answer)) fail(rel, `the answer must be exactly one sentence (found ${sentences.length})`);
      unique(firstSentences, answer.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim(), rel, "first sentence");
    }
    if (!/^```\w*$/m.test(raw)) fail(rel, "no code block");
    for (const h of ["Quick facts", kind.labels.cause, kind.labels.fix, "Example", kind.labels.mapping, "Related", "Source"]) if (!new RegExp(`^## ${h}$`, "m").test(raw)) fail(rel, `missing the "${h}" section`);
    const src = raw.split(/^## Source$/m)[1] ?? "";
    if (!/\]\(https:\/\/[^)\s]+\)/.test(src)) fail(rel, "no source link under Source");
    if (!/^Checked: \d{4}-\d{2}-\d{2}$/m.test(src)) fail(rel, "no checked date under Source");
    if (!/^\*(Compile-checked|Run-checked|Not compiled)/m.test(raw)) fail(rel, "the code block has no compile or run note (Compile-checked, Run-checked or Not compiled)");
    const related = (raw.split(/^## Related$/m)[1] ?? "").split(/^## /m)[0];
    if ((related.match(/\]\(/g) ?? []).length < 2) fail(rel, "fewer than two related links");
    if (/\b(TODO|TBD|lorem ipsum)\b/i.test(raw)) fail(rel, "placeholder text");
    const words = wordCount(raw);
    if (words < MIN_WORDS) fail(rel, `thin page (${words} words, minimum ${MIN_WORDS}); do not generate it, or mark the entry draft`);
    if (!meta?.label) fail(rel, "frontmatter needs a label (the sidebar text)");
  }
  const readme = join(dir, "README.md");
  if (existsSync(readme) && readFileSync(readme, "utf8") !== renderIndex(kind, entries)) fail(`docs/${kind.id}/README.md`, "differs from the data files; run npm run build:errors");
  if (!existsSync(readme) && entries.length) fail(`docs/${kind.id}/README.md`, "missing; run npm run build:errors");
  total += files.length;
}

if (problems.length) {
  console.error(`${problems.length} reference-page problem(s):\n${problems.map((p) => `  - ${p}`).join("\n")}`);
  process.exit(1);
}
console.log(`Reference pages OK: ${total} pages (${KINDS.map((k) => `${all.filter((p) => p.kind === k.id).length} ${k.id}`).join(", ")}) have a vendor source, a code block, a cause, a fix, a unique one-sentence answer and at least ${MIN_WORDS} words.`);
