// RevenueDot: open-source, self-hostable alternative to RevenueCat. Same SDK API, free.
// This file: the quality gate for docs/errors/*.md. Fails a page that has no source link, no code block, a first sentence
// shared with another page, no cause or fix, a missing compile note, thin content, or text that differs from the data file.
// Run: npm run check:errors
// Docs: https://revenuedot.app/docs/errors   Migrate from RevenueCat: https://revenuedot.app/docs/migrate
import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { GENERATED, MIN_WORDS, OUT_DIR, loadData, renderIndex, renderPage, validateEntry, wordCount } from "./lib/errors.mjs";
import { proseLines, readPage } from "./lib/pages.mjs";

const problems = [];
const fail = (rel, msg) => problems.push(`${rel}: ${msg}`);
const sets = loadData();
const all = sets.flatMap((s) => s.pages).filter((p) => !p.draft);
const bySlug = new Map(all.map((p) => [p.slug, p]));
const files = existsSync(OUT_DIR) ? readdirSync(OUT_DIR).filter((f) => f.endsWith(".md") && f !== "README.md") : [];

// Every non-draft entry has a page, and every page has an entry.
for (const p of all) if (!files.includes(`${p.slug}.md`)) fail(`data/errors/${p.file}`, `${p.slug} has no generated page; run npm run build:errors`);
for (const f of files) if (!bySlug.has(f.replace(/\.md$/, ""))) fail(`docs/errors/${f}`, "no entry in data/errors (stale or hand-written page)");

const firstSentences = new Map();
for (const f of files) {
  const rel = `docs/errors/${f}`;
  const slug = f.replace(/\.md$/, "");
  const entry = bySlug.get(slug);
  const { raw, meta, body } = readPage(rel);
  if (!raw.includes(GENERATED)) fail(rel, "not generated by scripts/gen-errors.mjs");
  if (entry) {
    for (const m of validateEntry(entry, new Set(bySlug.keys()))) fail(rel, m);
    if (raw !== renderPage(entry, bySlug)) fail(rel, "differs from its data file; run npm run build:errors (never edit these pages by hand)");
  }
  const lines = proseLines(body).map((x) => x.line);
  const h1 = lines.findIndex((l) => /^#\s/.test(l));
  // The answer: the first paragraph after the H1.
  const para = [];
  for (const l of lines.slice(h1 + 1)) { if (!l.trim()) { if (para.length) break; continue; } if (/^#{1,6}\s/.test(l)) break; para.push(l.trim()); }
  const answer = para.join(" ");
  if (!answer) fail(rel, "no answer sentence under the H1");
  else {
    const sentences = answer.match(/[^.!?]+[.!?]+(\s|$)/g) ?? [];
    if (sentences.length !== 1 || !/[.!?]$/.test(answer)) fail(rel, `the answer must be exactly one sentence (found ${sentences.length})`);
    const key = answer.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
    if (firstSentences.has(key)) fail(rel, `first sentence is the same as ${firstSentences.get(key)}`);
    firstSentences.set(key, rel);
  }
  if (!/^```\w*$/m.test(raw)) fail(rel, "no code block");
  for (const h of ["Quick facts", "Cause", "Fix", "Example", "Related", "Source"]) if (!new RegExp(`^## ${h}$`, "m").test(raw)) fail(rel, `missing the "${h}" section`);
  const src = raw.split(/^## Source$/m)[1] ?? "";
  if (!/\]\(https:\/\/[^)\s]+\)/.test(src)) fail(rel, "no source link under Source");
  if (!/^Checked: \d{4}-\d{2}-\d{2}$/m.test(src)) fail(rel, "no checked date under Source");
  if (!/^\*(Compile-checked|Not compiled)/m.test(raw)) fail(rel, "the code block has no compile note (Compile-checked or Not compiled)");
  const related = (raw.split(/^## Related$/m)[1] ?? "").split(/^## /m)[0];
  if ((related.match(/\]\(/g) ?? []).length < 2) fail(rel, "fewer than two related links");
  if (/\b(TODO|TBD|lorem ipsum)\b/i.test(raw)) fail(rel, "placeholder text");
  const words = wordCount(raw);
  if (words < MIN_WORDS) fail(rel, `thin page (${words} words, minimum ${MIN_WORDS}); do not generate it, or mark the entry draft`);
  if (!meta?.label) fail(rel, "frontmatter needs a label (the sidebar text)");
}
if (existsSync(OUT_DIR) && readFileSync(join(OUT_DIR, "README.md"), "utf8") !== renderIndex(all)) fail("docs/errors/README.md", "differs from the data files; run npm run build:errors");

if (problems.length) {
  console.error(`${problems.length} error-page problem(s):\n${problems.map((p) => `  - ${p}`).join("\n")}`);
  process.exit(1);
}
console.log(`Error pages OK: ${files.length} pages have a source link, a code block, a cause, a fix, a unique one-sentence answer and at least ${MIN_WORDS} words.`);
